#!/usr/bin/env bash
#configure web-02 to be identical to web-01
#Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02
#the name of the custom HTTP header must be X-Served-By

sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i "/server_name _;/a add_header X-Served-By '$HOSTNAME';" /etc/nginx/sites-available/default
sudo service nginx restart
