#!/usr/bin/env bash
#instal a load balancer (HAproxy)

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 14231-web-01 100.25.48.93:80 check\n\tserver 14231-web-02 34.229.71.18:80 check" >> /etc/haproxy/haproxy.cfg 
sudo service haproxy restart
