#!/usr/bin/env bash
# displays username, user id and home directory for each line of /etc/passwd.

input="/etc/passwd"
while IFS= read -r passwd
do
    echo "$passwd" | cut -d':' -f1,3,6
done < "$input"
