#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 20 and:
for i in {1..20}
do
case $i in "4")
	echo $i
	echo "bad luck from china"
	;;
"9")
	echo $i
	echo "bad luck from japan"
	;;
"17")
	echo $i
	echo "bad luck from italy"
	;;
*)
echo $i
;;
esac
done
