#!/usr/bin/env bash
#A Bash script that configures an Ubuntu server with the below requirements.
#Requirements:

#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.
#first we copy /etc/hosts
#we search through the copy
#find localhost (127.*) and replace
#add facebook 8.8.8.8
#copy the copy to /etc/hosts
cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
