#!/usr/bin/env bash
#A Bash script that configures an Ubuntu server with the below requirements.
#Requirements:

#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.
#first we copy /etc/hosts
#we search through the copy
#find localhost (127.*) and replace
#add facebook 8.8.8.8
#copy the copy to /etc/hosts

#cp /etc/hosts ~/hosts_new
#sed -i s/^127.*/"127.0.0.2 localhost"/ ~/hosts_new
#echo "8.8.8.8.8 facebook.com" >> ~/hosts_new
#cp ~/hosts_new /etc/hosts

# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

cp /etc/hosts hosts_new
sed -i s/^127.*/"127.0.0.2 localhost"/ hosts_new
echo "8.8.8.8 facebook.com" >> hostw_new
cp hosts_new /etc/hosts
